### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YourFavFem** [Lemonszz/LemonLib#2]
Trapexpansion 1.13.2

Forge 1.13.2

Does this issue occur on the latest version of Forge? (Yes)

Crash Log (No, I didn't get one. It just sad to me that my Game crashed)

When starting a World with this Mod (LemonLib) the Game crashes instantly

**Comment by Lemonszz** [comment]
I can't really help without a crashlog, there's should be a "latest.log" file in the logs folder in  your installation directory.

**Comment by Lemonszz** [comment]
Closing this as no crash log was givin

**Comment by Flo2018v** [comment]
Hi, I am not the person who started this thread, but I can tell you the issue does occur. However, when ran on a server, the mod causes no problems. Once ran on a client, the issue happends, causing the player to leave the game once spawned due to “unsupported mods” I could provide you the error message as well as the logs if you want. Just let me know where I can send you them!


EDIT: I should also mention that the error is not related to the trapexpension mod, as it occurs every time, even if the only mod installed on the client is lemonlib

**Comment by Lemonszz** [comment]
Hm, that's strange.

If you could put the log on a website like pastebin (https://pastebin.com/) or gist (https://gist.github.com/) and link them here, that would be very helpful.

**Comment by Flo2018v** [comment]
Alright. I will do that. But not now. Probably tommorow, as it’s kinda late and I got some other things to do. Bump me back if I forget tommorow
